Controllers/DocumentosController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TuFicha.Models;

namespace TuFicha.Controllers
{
    [Authorize]
    public class DocumentosController : Controller
    {

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private ApplicationDbContext db = new ApplicationDbContext();


        public DocumentosController()
        {
        }

        public DocumentosController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        // GET: Documentos
        public ActionResult Index()
        {
            string email = "";
            ApplicationUser usuario = new ApplicationUser();
            if (User.Identity.IsAuthenticated)
            {
                email = User.Identity.Name;
                usuario = UserManager.FindByEmail(email);
                ViewBag.Nombre = usuario.Nombre + " " + usuario.Apellidos;
                ViewBag.Rut = usuario.Rut;
                ViewBag.Edad = "16";
            }
            else
            {
                ViewBag.Nombre = "Carlos Latorre Vargas";
                ViewBag.Rut = "11111111-3";
                ViewBag.Edad = "26 años";
            }


            List<FichaUsuario> fichaUsuario = db.FichaUsuario.Where(x => x.UserId == usuario.Id).ToList();

            List<FichaDocumentos> fichaDocumentos = new List<FichaDocumentos>();

            var documentos = new List<Documentos>();

            foreach (var item in fichaUsuario)
            {
                fichaDocumentos.Add(db.FichaDocumentos.Where(x => x.IdFichaUsuario == item.IdFichaUsuario).FirstOrDefault());
            }

            foreach (var item in fichaDocumentos)
            {
                documentos.Add(db.Documentos.Where(x => x.IdDocumento == item.IdFichaUsuario).FirstOrDefault());
            }

            
            return View(documentos.ToList());
        }

        // GET: Documentos/Details/5
        public ActionResult Details(int? id)
        {
            string email = "";
            ApplicationUser usuario = new ApplicationUser();
            if (User.Identity.IsAuthenticated)
            {
                email = User.Identity.Name;
                usuario = UserManager.FindByEmail(email);
                ViewBag.Nombre = usuario.Nombre + " " + usuario.Apellidos;
                ViewBag.Rut = usuario.Rut;
                ViewBag.Edad = "16";
            }
            else
            {
                ViewBag.Nombre = "Carlos Latorre Vargas";
                ViewBag.Rut = "11111111-3";
                ViewBag.Edad = "26 años";
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Documentos documentos = db.Documentos.Find(id);
            if (documentos == null)
            {
                return HttpNotFound();
            }
            return View(documentos);
        }

        // GET: Documentos/Create
        public ActionResult Create()
        {
            string email = "";
            ApplicationUser usuario = new ApplicationUser();
            if (User.Identity.IsAuthenticated)
            {
                email = User.Identity.Name;
                usuario = UserManager.FindByEmail(email);
                ViewBag.Nombre = usuario.Nombre + " " + usuario.Apellidos;
                ViewBag.Rut = usuario.Rut;
                ViewBag.Edad = "16";
            }
            else
            {
                ViewBag.Nombre = "Carlos Latorre Vargas";
                ViewBag.Rut = "11111111-3";
                ViewBag.Edad = "26 años";
            }

            ViewBag.IdCentroMedico = new SelectList(db.CentroMedico, "IdCentroMedico", "CM_Nombre");
            ViewBag.IdProfesional = new SelectList(db.ProfesionalSalud, "IdProfesional", "Pro_Nombre");
            ViewBag.IdTipoDocumento = new SelectList(db.TipoDocumento, "IdTipoDocumento", "TD_Nombre");
            return View();
        }

        // POST: Documentos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdDocumento,Doc_Nombre,Doc_Descripcion,IdProfesional,IdCentroMedico,IdTipoDocumento,archivo")] Documentos documentos)
        {
            string email2 = "";
            ApplicationUser usuario2 = new ApplicationUser();
            if (User.Identity.IsAuthenticated)
            {
                email2 = User.Identity.Name;
                usuario2 = UserManager.FindByEmail(email2);
                ViewBag.Nombre = usuario2.Nombre + " " + usuario2.Apellidos;
                ViewBag.Rut = usuario2.Rut;
                ViewBag.Edad = (DateTime.Now - usuario2.FechaNacimiento).TotalHours;
            }
            else
            {
                ViewBag.Nombre = "Carlos Latorre Vargas";
                ViewBag.Rut = "11111111-3";
                ViewBag.Edad = "26 años";
            }


            if (ModelState.IsValid)
            {
                string email = "";
                ApplicationUser usuario = new ApplicationUser();
                email = User.Identity.Name;
                usuario = UserManager.FindByEmail(email);
                try
                {
                    string fileExt = Path.GetExtension(documentos.archivo.FileName);
                    documentos.Extension = fileExt;
                    string rutaCentral = Server.MapPath("~/");
                    string nombreArchivo = Path.GetFileNameWithoutExtension(documentos.archivo.FileName);
                    string nombreFinal = String.Format("Files/{0}_{1}{2}", usuario.Id, nombreArchivo, fileExt);
                    string rutaCompleta = Path.Combine(rutaCentral, nombreFinal);
                    documentos.archivo.SaveAs(rutaCompleta);
                    string rutaToWatch = "https://localhost:44348/" + nombreFinal;
                    documentos.ruta = rutaToWatch;
                    documentos.Doc_FechaCreacion = DateTime.Now;
                    db.Documentos.Add(documentos);
                    db.SaveChanges();
                    UserDocumento userDocumento = new UserDocumento()
                    {
                        IdDocumento = documentos.IdDocumento,
                        UserId = usuario.Id
                    };
                    db.UserDocumento.Add(userDocumento);
                    db.SaveChanges();      

                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    throw ex;
                }
                
            }

            ViewBag.IdCentroMedico = new SelectList(db.CentroMedico, "IdCentroMedico", "CM_Nombre", documentos.IdCentroMedico);
            ViewBag.IdProfesional = new SelectList(db.ProfesionalSalud, "IdProfesional", "Pro_Nombre", documentos.IdProfesional);
            ViewBag.IdTipoDocumento = new SelectList(db.TipoDocumento, "IdTipoDocumento", "TD_Nombre", documentos.IdTipoDocumento);
            return View(documentos);
        }

        // GET: Documentos/Edit/5
        public ActionResult Edit(int? id)
        {
            string email2 = "";
            ApplicationUser usuario2 = new ApplicationUser();
            if (User.Identity.IsAuthenticated)
            {
                email2 = User.Identity.Name;
                usuario2 = UserManager.FindByEmail(email2);
                ViewBag.Nombre = usuario2.Nombre + " " + usuario2.Apellidos;
                ViewBag.Rut = usuario2.Rut;
                ViewBag.Edad = (DateTime.Now - usuario2.FechaNacimiento).TotalHours;
            }
            else
            {
                ViewBag.Nombre = "Carlos Latorre Vargas";
                ViewBag.Rut = "11111111-3";
                ViewBag.Edad = "26 años";
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Documentos documentos = db.Documentos.Find(id);
            if (documentos == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCentroMedico = new SelectList(db.CentroMedico, "IdCentroMedico", "CM_Nombre", documentos.IdCentroMedico);
            ViewBag.IdProfesional = new SelectList(db.ProfesionalSalud, "IdProfesional", "Pro_Nombre", documentos.IdProfesional);
            ViewBag.IdTipoDocumento = new SelectList(db.TipoDocumento, "IdTipoDocumento", "TD_Nombre", documentos.IdTipoDocumento);
            return View(documentos);
        }

        // POST: Documentos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

Views/Documentos/Create.cshtml
@model TuFicha.Models.Documentos

@{
    ViewBag.Title = "Create";
}

<h2>Nuevo Documento</h2>


@using (Html.BeginForm("Create","Documentos", FormMethod.Post, new { name = "formDocs", id = "formDocs", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="hpanel">
        <div class="panel-body">
            <div class="row">
                <div class="form-horizontal">
                    <div class="col-lg-7">
                        <h4>Documentos</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Doc_Nombre, htmlAttributes: new { @class = "control-label col-md-2", @style = "text-align: left;" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Doc_Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Doc_Nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Doc_Descripcion, htmlAttributes: new { @class = "control-label col-md-2", @style = "text-align: left;" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Doc_Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Doc_Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IdProfesional, "Profesional Salud", htmlAttributes: new { @class = "control-label col-md-2", @style = "text-align: left;" })
                            <div class="col-md-10">
                                @Html.DropDownList("IdProfesional", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IdProfesional, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IdCentroMedico, "Centro médico", htmlAttributes: new { @class = "control-label col-md-2", @style = "text-align: left;" })
                            <div class="col-md-10">
                                @Html.DropDownList("IdCentroMedico", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IdCentroMedico, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IdTipoDocumento, "Tipo Documento", htmlAttributes: new { @class = "control-label col-md-2", @style = "text-align: left;" })
                            <div class="col-md-10">
                                @Html.DropDownList("IdTipoDocumento", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IdTipoDocumento, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-5">
                        <div class="form-group">
                            <div class="col-md-12">
                                <div class="row m-t-lg m-b-lg"></div>
                                <div class="row">
                                    <p>Archivo a Cargar</p>
                                </div>
                                <div class="row">
                                    <input id="archivo" name="archivo" type="file" class="upload" />
                                </div>                                
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>

    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Documentos/Delete.cshtml
@model TuFicha.Models.Documentos

@{
    ViewBag.Title = "Delete";
}

<h2>Borrar Documento</h2>

<h3>¿Está seguro de borrar este Documento? No se podrá acceder a él despues de borrarlo</h3>
<div>
    <h4>Documento:</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CentroMedico.CM_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CentroMedico.CM_Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfesionalSalud.Pro_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfesionalSalud.Pro_Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoDocumento.TD_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDocumento.TD_Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doc_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doc_Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doc_FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doc_FechaCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Extension)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Extension)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doc_Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doc_Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="borrar" class="btn btn-danger" /> |
            @Html.ActionLink("Volver", "Index")
        </div>
    }
</div>

Views/Documentos/Details.cshtml
@model TuFicha.Models.Documentos

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Documentos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CentroMedico.CM_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CentroMedico.CM_Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfesionalSalud.Pro_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfesionalSalud.Pro_Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoDocumento.TD_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDocumento.TD_Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doc_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doc_Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doc_FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doc_FechaCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Extension)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Extension)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doc_Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doc_Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdDocumento }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Documentos/Edit.cshtml
@model TuFicha.Models.Documentos

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Documentos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdDocumento)

        <div class="form-group">
            @Html.LabelFor(model => model.Doc_Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doc_Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doc_Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doc_FechaCreacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doc_FechaCreacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doc_FechaCreacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Extension, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Extension, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Extension, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doc_Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doc_Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doc_Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdProfesional, "IdProfesional", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProfesional", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProfesional, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCentroMedico, "IdCentroMedico", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdCentroMedico", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCentroMedico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoDocumento, "IdTipoDocumento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoDocumento", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Documentos/Index.cshtml
@model IEnumerable<TuFicha.Models.Documentos>

@{
    ViewBag.Title = "Index";
}

<h2>Documentos</h2>

<p>
    @Html.ActionLink("Añadir nuevo", "Create",null, new { @class = "btn btn-sm btn-success"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CentroMedico.CM_Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProfesionalSalud.Pro_Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoDocumento.TD_Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doc_Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doc_FechaCreacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Extension)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doc_Descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CentroMedico.CM_Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProfesionalSalud.Pro_Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoDocumento.TD_Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Doc_Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Doc_FechaCreacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Extension)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Doc_Descripcion)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.IdDocumento }, new { @class = "btn btn-xs btn-warning"}) |
            @Html.ActionLink("Detalle", "Details", new { id=item.IdDocumento }, new { @class = "btn btn-xs btn-info" }) |
            @Html.ActionLink("Borrar", "Delete", new { id=item.IdDocumento }, new { @class = "btn btn-xs btn-danger" })
        </td>
    </tr>
}

</table>