Models/DatosUsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TuFicha.Models
{
    public class DatosUsuarioViewModel
    {

        public List<FichaUsuario> fichaUsuario {get; set;}
        public List<UserDocumento> documentosUsuario { get; set; }


    }
}

Models/WatchDocViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TuFicha.Models
{
    public class WatchDocViewModel
    {
        public ApplicationUser user { get; set; }
        public List<FichaDocumentos> documentos { get; set; }
    }
}

Controllers/LinkUsuarioController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TuFicha.Models;

namespace TuFicha.Controllers
{
    [Authorize]
    public class LinkUsuarioController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private ApplicationDbContext db = new ApplicationDbContext();


        public LinkUsuarioController()
        {
        }

        public LinkUsuarioController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: LinkUsuarios
        public ActionResult Index()
        {
            string email = "";
            ApplicationUser usuario = new ApplicationUser();
            if (User.Identity.IsAuthenticated)
            {
                email = User.Identity.Name;
                usuario = UserManager.FindByEmail(email);
                ViewBag.Nombre = usuario.Nombre + " " + usuario.Apellidos;
                ViewBag.Rut = usuario.Rut;
                ViewBag.Edad = (((DateTime.Now - usuario.FechaNacimiento).TotalDays) / 365).ToString("0");
            }
            else
            {
                ViewBag.Nombre = "Carlos Latorre Vargas";
                ViewBag.Rut = "11111111-3";
                ViewBag.Edad = "26 años";
            }

            var linkUsuario = db.LinkUsuario.Where(x => x.UserId == usuario.Id).Include(l => l.FichaUsuario);
            return View(linkUsuario.ToList());
        }

        // GET: LinkUsuarios/Details/5
        public ActionResult Details(int? id)
        {
            string email2 = "";
            ApplicationUser usuario2 = new ApplicationUser();
            if (User.Identity.IsAuthenticated)
            {
                email2 = User.Identity.Name;
                usuario2 = UserManager.FindByEmail(email2);
                ViewBag.Nombre = usuario2.Nombre + " " + usuario2.Apellidos;
                ViewBag.Rut = usuario2.Rut;
                ViewBag.Edad = (((DateTime.Now - usuario2.FechaNacimiento).TotalDays) / 365).ToString("0");
            }
            else
            {
                ViewBag.Nombre = "Carlos Latorre Vargas";
                ViewBag.Rut = "11111111-3";
                ViewBag.Edad = "26 años";
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LinkUsuario linkUsuario = db.LinkUsuario.Find(id);
            if (linkUsuario == null)
            {
                return HttpNotFound();
            }
            return View(linkUsuario);
        }

        // GET: LinkUsuarios/Create
        public ActionResult Create()
        {
            string email2 = "";
            ApplicationUser usuario2 = new ApplicationUser();
            if (User.Identity.IsAuthenticated)
            {
                email2 = User.Identity.Name;
                usuario2 = UserManager.FindByEmail(email2);
                ViewBag.Nombre = usuario2.Nombre + " " + usuario2.Apellidos;
                ViewBag.Rut = usuario2.Rut;
                ViewBag.Edad = (((DateTime.Now - usuario2.FechaNacimiento).TotalDays) / 365).ToString("0");
            }
            else
            {
                ViewBag.Nombre = "Carlos Latorre Vargas";
                ViewBag.Rut = "11111111-3";
                ViewBag.Edad = "26 años";
            }

            ViewBag.IdHorario = new SelectList(db.Horarios, "IdHorario", "horas");
            ViewBag.IdFichaUsuario = new SelectList(db.FichaUsuario, "IdFichaUsuario", "FU_Nombre");

            LinkUsuario linkUsuario = new LinkUsuario()
            {
                Codigo = RandomString(6)
            };

            return View(linkUsuario);
        }

        // POST: LinkUsuarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdLink,Codigo,IdFichaUsuario,IdHorario")] LinkUsuario linkUsuario)
        {
            string email2 = "";
            ApplicationUser usuario2 = new ApplicationUser();
            if (User.Identity.IsAuthenticated)
            {
                email2 = User.Identity.Name;
                usuario2 = UserManager.FindByEmail(email2);
                ViewBag.Nombre = usuario2.Nombre + " " + usuario2.Apellidos;
                ViewBag.Rut = usuario2.Rut;
                ViewBag.Edad = (((DateTime.Now - usuario2.FechaNacimiento).TotalDays) / 365).ToString("0");
            }
            else
            {
                ViewBag.Nombre = "Carlos Latorre Vargas";
                ViewBag.Rut = "11111111-3";
                ViewBag.Edad = "26 años";
            }

            if (ModelState.IsValid)
            {
                Horarios horarios = db.Horarios.Find(linkUsuario.IdHorario);
                linkUsuario.LU_FechaCreacion = DateTime.Now;
                linkUsuario.horas = Int32.Parse(horarios.horas.ToString());
                linkUsuario.FechaVencimiento = DateTime.Now.AddHours(horarios.horas);
                linkUsuario.UserId = usuario2.Id;

                db.LinkUsuario.Add(linkUsuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdFichaUsuario = new SelectList(db.FichaUsuario, "IdFichaUsuario", "FU_Nombre", linkUsuario.IdFichaUsuario);
            return View(linkUsuario);
        }

        // GET: LinkUsuarios/Edit/5
        public ActionResult Edit(int? id)
        {
            string email2 = "";
            ApplicationUser usuario2 = new ApplicationUser();
            if (User.Identity.IsAuthenticated)
            {
                email2 = User.Identity.Name;
                usuario2 = UserManager.FindByEmail(email2);
                ViewBag.Nombre = usuario2.Nombre + " " + usuario2.Apellidos;
                ViewBag.Rut = usuario2.Rut;
                ViewBag.Edad = (((DateTime.Now - usuario2.FechaNacimiento).TotalDays) / 365).ToString("0");
            }
            else
            {
                ViewBag.Nombre = "Carlos Latorre Vargas";
                ViewBag.Rut = "11111111-3";
                ViewBag.Edad = "26 años";
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LinkUsuario linkUsuario = db.LinkUsuario.Find(id);
            if (linkUsuario == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdFichaUsuario = new SelectList(db.FichaUsuario, "IdFichaUsuario", "FU_Nombre", linkUsuario.IdFichaUsuario);
            return View(linkUsuario);
        }

        // POST: LinkUsuarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdLink,Codigo,horas,FechaVencimiento,LU_FechaCreacion,IdFichaUsuario")] LinkUsuario linkUsuario)
        {
            string email2 = "";
            ApplicationUser usuario2 = new ApplicationUser();
            if (User.Identity.IsAuthenticated)
            {
                email2 = User.Identity.Name;
                usuario2 = UserManager.FindByEmail(email2);
                ViewBag.Nombre = usuario2.Nombre + " " + usuario2.Apellidos;
                ViewBag.Rut = usuario2.Rut;
                ViewBag.Edad = (((DateTime.Now - usuario2.FechaNacimiento).TotalDays) / 365).ToString("0");
            }
            else
            {
                ViewBag.Nombre = "Carlos Latorre Vargas";
                ViewBag.Rut = "11111111-3";
                ViewBag.Edad = "26 años";
            }

            if (ModelState.IsValid)
            {
                db.Entry(linkUsuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdFichaUsuario = new SelectList(db.FichaUsuario, "IdFichaUsuario", "FU_Nombre", linkUsuario.IdFichaUsuario);
            return View(linkUsuario);
        }

        // GET: LinkUsuarios/Delete/5
        public ActionResult Delete(int? id)
        {
            string email2 = "";
            ApplicationUser usuario2 = new ApplicationUser();
            if (User.Identity.IsAuthenticated)
            {
                email2 = User.Identity.Name;
                usuario2 = UserManager.FindByEmail(email2);
                ViewBag.Nombre = usuario2.Nombre + " " + usuario2.Apellidos;
                ViewBag.Rut = usuario2.Rut;
                ViewBag.Edad = (((DateTime.Now - usuario2.FechaNacimiento).TotalDays) / 365).ToString("0");
            }
            else
            {

Views/LinkUsuario/Create.cshtml
@model TuFicha.Models.LinkUsuario

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="hpanel">
        <div class="panel-heading">
            <h2>Nuevo código</h2>
        </div>
        <div class="panel-body">
            
            <div class="form-horizontal">
                <div class="row">
                    <div class="col-md-3">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.IdHorario,"Duración",htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.DropDownList("IdHorario", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IdHorario, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.IdFichaUsuario, "Ficha a compartir", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.DropDownList("IdFichaUsuario", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IdFichaUsuario, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Generar" class="btn btn-sm btn-info" />
                            </div>
                        </div>
                    </div>
                </div>  
            </div>
        </div>
    </div>

    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/LinkUsuario/Delete.cshtml
@model TuFicha.Models.LinkUsuario

@{
    ViewBag.Title = "Delete";
}

<h2>Borrar Código</h2>

<h3>¿Está seguro de borrar este Código? Ya no será válido cuando se borre.</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FichaUsuario.FU_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FichaUsuario.FU_Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.horas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.horas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaVencimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaVencimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LU_FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LU_FechaCreacion)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/LinkUsuario/Details.cshtml
@model TuFicha.Models.LinkUsuario

@{
    ViewBag.Title = "Details";
}

<h2>Detalle</h2>

<div>
    <h4>Mi Código</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FichaUsuario.FU_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FichaUsuario.FU_Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.horas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.horas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaVencimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaVencimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LU_FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LU_FechaCreacion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdLink }, new { @class = "btn btn-warning"}) |
    @Html.ActionLink("Volver", "Index",null, new { @class = "btn btn-default"})
</p>

Views/LinkUsuario/Edit.cshtml
@model TuFicha.Models.LinkUsuario

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LinkUsuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdLink)

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.horas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.horas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.horas, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LU_FechaCreacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LU_FechaCreacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LU_FechaCreacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdFichaUsuario, "IdFichaUsuario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdFichaUsuario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdFichaUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/LinkUsuario/Index.cshtml
@model IEnumerable<TuFicha.Models.LinkUsuario>

@{
    ViewBag.Title = "Index";
}

<h2>Listado de Códigos</h2>

<p>
    @Html.ActionLink("Nuevo código", "Create",null,new { @class = "btn btn-sm btn-success"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FichaUsuario.FU_Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.horas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaVencimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LU_FechaCreacion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FichaUsuario.FU_Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.horas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaVencimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LU_FechaCreacion)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.IdLink }) |*@
            @Html.ActionLink("Details", "Details", new { id=item.IdLink }, new { @class = "btn btn-xs btn-primary" }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdLink }, new { @class = "btn btn-xs btn-danger" })
        </td>
    </tr>
}

</table>

Views/LinkUsuario/InsertCodigo.cshtml
@using TuFicha.Models
@model CodigoViewModel
@{
    Layout = "~/Views/Shared/_LayoutLogin.cshtml"; ;
}
@{
    ViewBag.Title = "TuFicha";
}



<div class="row m-t-lg">
</div><br /><br /><br />
<div class="login-container m-t-xl m-b-xl">
    <div class="row">
        <div class="col-md-12">
            <div class="hpanel" style="height: 100%;">
                <div class="panel-body" style="height: 100%;">
                    <div class="col-lg-12">
                        <section id="loginForm">
                            @using (Html.BeginForm("WatchDocs", "LinkUsuario", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="m-t-lg text-center">
                                    <h2 style="color:grey;">Bienvenido a TuFicha.cl</h2>
                                </div>
                                <br />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group text-center">
                                    <div class="col-md-1"></div>
                                    @Html.LabelFor(m => m.codigo,"Ingresa tú código a continuación:", new { @class = "col-md-11 control-label", @style= "text-align: left; color:gray;"})
                                    
                                    <div class="col-md-1"></div>
                                    <div class="col-md-10">                                        
                                        @Html.TextBoxFor(m => m.codigo, new { @class = "form-control", @placeholder = "Ej: XP09AK2" })
                                        @Html.ValidationMessageFor(m => m.codigo, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-1 col-md-10">
                                        <input type="submit" style="width:100%;" value="Ingresar" class="btn btn-lg btn-info" />
                                    </div>
                                </div><br /><hr />
                                <div class="text-center">
                                    <p>
                                        ¿Eres un paciente nuevo?  @Html.ActionLink("Registrate aquí", "Register", "Account")
                                    </p>
                                </div>
                                <div class="text-center">
                                    <p>
                                        ¿Tienes cuenta? @Html.ActionLink("Ingresa aquí", "Login", "Account")
                                    </p>
                                </div><br />

                                @* Habilite esta opción una vez tenga la confirmación de la cuenta habilitada para la funcionalidad de restablecimiento de contraseña
                                    <p>
                                        @Html.ActionLink("¿Ha olvidado su contraseña?", "ForgotPassword")
                                    </p>*@
                            }
                        </section>

                            @*<div class="col-md-4">
                                <section id="socialLoginForm">
                                    @Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
                                </section>
                            </div>*@
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Views/LinkUsuario/WatchDocs.cshtml
@model TuFicha.Models.WatchDocViewModel
@{
    ViewBag.Title = "Home Page";
}

@{
    Layout = "~/Views/Shared/_LayoutWatch.cshtml"; ;
}

<div class="row m-t-lg">
    <div class="hpanel">
        <div class="panel-body">
            <div class="col-lg-12">
                @Html.Partial("_DatosUsuario", Model)
            </div>
        </div>
    </div>
</div>

Views/LinkUsuario/_DatosUsuario.cshtml
@model TuFicha.Models.WatchDocViewModel


<div class="row">
    <div class="hpanel">
        <div class="row">
            <div>
                <h4>Datos Paciente:</h4>
            </div>
            <div class="col-lg-12">
                @if (Model.user != null)
                {
                        <div class="col-lg-6 m-l-md">
                            <div>
                                <div class="row img-thumbnail text-center" style="width: 100%;">
                                    <h5>@Model.user.Nombre @Model.user.Apellidos</h5>
                                    <div class="row">
                                        <div>
                                            <p>Edad: @ViewBag.Edad</p>
                                            <p>Rut: @ViewBag.Rut</p>
                                            <p>Email: @Model.user.Email</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                }
            </div>
        </div>
        <br />
        <div class="row">
            <div>
                <h2>Sus Documentos</h2>
            </div>
            <div class="col-lg-12">
                @if (Model.documentos != null)
                {
                    foreach (var item in Model.documentos)
                    {
                        string[] texto = item.Documentos.Extension.Split('.');
                        string extSinPunto = texto[1];
                        string text = "../images/" + extSinPunto + ".png";
                        <div class="col-lg-2 m-l-md">
                            <div class="row">
                                <div class="row img-thumbnail text-center">
                                    <a class="btn btn-default" href="@item.Documentos.ruta" target="_blank">
                                        <img style="height:50%; width:50%; margin-top: 15px; margin-bottom: 15px;" src='@text' />
                                    </a>
                                </div>
                                <div class="row">
                                    <div class="row m-l-xl">
                                        @*<a class="btn btn-xs btn-success" href="@item.Documentos.ruta" target="_blank"><i class="fa fa-glass"></i> Ver</a>*@
                                    </div>
                                    <div>
                                        <p><b>@item.Documentos.Doc_Nombre</b></p>
                                        <p>@item.Documentos.Doc_Descripcion</p>
                                        <p>@item.Documentos.Doc_FechaCreacion</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                    }
                }
               
            </div>
        </div>
    </div>
</div>